version: "3.7"

services:
  jupyter:
    env_file:
      - .env
    container_name: jupyter_notebook
    build:
      context: .
      args:
        - gittoken=$GIT_ACCESS_TOKEN
    volumes:
      - .:/mnt
    ports:
      - 8888:8888
